#Auto-generated by rails
#Modified by Rajeev Ravi 11/28 + 11/29- Updated the index method to retrieve the users magazine media.

#Summary: This controller handles the magazine media for the site. The main functionality of this controller
# is in the index method which is primarily used to filter out the media that belongs to the user.
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  #Accesses the user's magazines. Author:Rajeev Ravi
  def index
    @magazines = (GeneralMedium.joins(:magazine)).joins(:personal_media_parameters).where('personal_media_parameters.users_id =?', current_user.id)
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end


  # POST /magazines
  # POST /magazines.json
  def create

    @magazine = Magazine.new(magazine_params)
    respond_to do |format|
      if @magazine.save
        format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1
  # PATCH/PUT /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1
  # DELETE /magazines/1.json
  def destroy
    @magazine.destroy
    respond_to do |format|
      format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magazine_params
      params.require(:magazine).permit(:issue, :general_medias_id)
    end
end
