#Auto-generated by rails

#Summary: 
class UsersController < ApplicationController

    
	def show
	    @thisUser = User.find(params[:id])
	    @historylog = HistoryLog.where(users_id: params[:id]).last(10)
	    @followers = Follower.where(users_id: params[:id])

	    @currUserFollowers = nil
	    if @thisUser.id != current_user.id
	    	@currUserFollowers = Follower.where(users_id: current_user.id)
	    end
	end

end
