#Auto-generated by rails

#Summary: 
class UsersController < ApplicationController
	def show
	    @thisUser = User.find(params[:id])
	    @historyLogs = HistoryLog.where(users_id: params[:id]).last(10)
	    @followers = Follower.where(users_id: params[:id])

	    @privateAccount = Preference.find_by(users_id: params[:id])
	    if @privateAccount != nil
	    	@privateAccount = @privateAccount.privacy
	    end 
	    @currUserFollowers = nil
	    if @thisUser.id != current_user.id
	    	@currUserFollowers = Follower.where(users_id: current_user.id)
	    end
	end

end
