require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the followers controller
#Author: Alyssa Langhals added devise and removed unneccessary tests
class FollowersControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  setup do
    @music = followers(:one)
    sign_in users(:one)
  end
  
end
