require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the followers controller
#Author: Alyssa Langhals added devise and removed unneccessary tests
class FollowersControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  setup do
    @thisUser = users(:one)
    sign_in users(:one)
  end

  test 'should add follower' do
    post followers_url, params: {fTarget: 1}
    assert_response :redirect
  end
  
end
