require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the personal media parameters controller
#Author: Alyssa Langhals added devise and removed unneccessary tests
class PersonalMediaParametersControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  setup do
    @personal_media_parameter = personal_media_parameters(:one)
    sign_in users(:one)
  end

  test "should get index" do
    get personal_media_parameters_url
    assert_response :success
  end

  test "should get new" do
    get new_personal_media_parameter_url
    assert_response :success
  end


  test "should get edit" do
    get edit_personal_media_parameter_url(@personal_media_parameter)
    assert_response :success
  end

  test "should update personal_media_parameter" do
    patch personal_media_parameter_url(@personal_media_parameter), params: { personal_media_parameter: { comments: @personal_media_parameter.comments, currentStatus: @personal_media_parameter.currentStatus, favorite: @personal_media_parameter.favorite, general_media_id: @personal_media_parameter.general_media_id, replay: @personal_media_parameter.replay, score: @personal_media_parameter.score, source: @personal_media_parameter.source, users_id: @personal_media_parameter.users_id } }
    assert_response :success
  end

  test "should destroy personal_media_parameter" do
    assert_difference('PersonalMediaParameter.count', -1) do
      delete personal_media_parameter_url(@personal_media_parameter)
    end

    assert_redirected_to personal_media_parameters_url
  end
end
