require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the preferences controller
#Author: Alyssa Langhals added devise and removed unneccessary tests
class PreferencesControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  setup do
    @preference = preferences(:one)
    sign_in users(:one)
  end

  test "should get index" do
    get preferences_url
    assert_response :success
  end

  test "should get new" do
    get new_preference_url
    assert_response :success
  end

  test "should create preference" do
    assert_difference('Preference.count') do
      post preferences_url, params: { preference: { font: @preference.font, fontColor: @preference.fontColor, fontSize: @preference.fontSize, privacy: @preference.privacy, profilePicture: @preference.profilePicture, users_id: @preference.users_id, wallpaper: @preference.wallpaper } }
    end

    assert_redirected_to preference_url(Preference.last)
  end

  test "should show preference" do
    get preference_url(@preference)
    assert_response :success
  end

  test "should get edit" do
    get edit_preference_url(@preference)
    assert_response :success
  end

  test "should update preference" do
    patch preference_url(@preference), params: { preference: { font: @preference.font, fontColor: @preference.fontColor, fontSize: @preference.fontSize, privacy: @preference.privacy, profilePicture: @preference.profilePicture, users_id: @preference.users_id, wallpaper: @preference.wallpaper } }
    assert_redirected_to preference_url(@preference)
  end

  test "should destroy preference" do
    assert_difference('Preference.count', -1) do
      delete preference_url(@preference)
    end

    assert_redirected_to preferences_url
  end
end
