require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the users controller
#Author: Alyssa Langhals added devise and removed unneccessary tests
class UsersControllerTest < ActionDispatch::IntegrationTest
  # test "the truth" do
  #   assert true
  # end
end
