require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the custom media model
#Author: Alyssa Langhals 
class CustomMediumTest < ActiveSupport::TestCase
   test "create custom media" do
     media = CustomMedium.new(typeOfMedia: 'musical')
      assert_equal 'musical', media.typeOfMedia
   end
end
