require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the custom media entry model
#Author: Alyssa Langhals added devise and removed unneccessary tests
class CustomMediaEntryTest < ActiveSupport::TestCase
  test 'create entry' do
    entry = CustomMediaEntry.new(key: 'age', value: '22')
    assert_equal 'age', entry.key
    assert_equal '22', entry.value
  end
end
