require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the general media model
#Author: Alyssa Langhals
class GeneralMediumTest < ActiveSupport::TestCase
   test "create general media" do
     media = GeneralMedium.new(name: 'Without YOU')
      assert_equal 'Without YOU', media.name
   end
end
