require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the history log model
#Author: Alyssa Langhals added devise and removed unneccessary tests
class HistoryLogTest < ActiveSupport::TestCase
  test 'create history log' do
    log = HistoryLog.new(historyMessage: "Created on")
    assert_equal "Created on", log.historyMessage
  end
end
