require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the magazine model
#Author: Alyssa Langhals added devise and removed unneccessary tests
class MagazineTest < ActiveSupport::TestCase
   test "create magazine" do
      mag = Magazine.new(issue: 1)
     assert_equal 1, mag.issue
   end
end
