require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the music model
#Author: Alyssa Langhals 
class MusicTest < ActiveSupport::TestCase
   test "create music" do
      music = Music.new(artist: 'Adele', album: '21')
      assert_equal 'Adele', music.artist
      assert_equal '21', music.album
   end
end
