require 'test_helper'
#Auto-generated by rails
#Summary: Contains tests for the video game model
#Author: Alyssa Langhals
class VideoGameTest < ActiveSupport::TestCase
   test "create video game" do
      game = VideoGame.new(studio: "Ghibli", system: 'xbox')
     assert_equal 'xbox', game.system
   end
end
